### ISSUE TITLE
Выгружаются люди, у которых было отменено пожертвование

### ISSUE THREAD

**Issue by andrey-makhnutin** [greenpeace/gpru_decline_calls#3]
Можно увидеть, если выставить `test_today_date` в `2017-04-04`
Выгружается донор 339257
Хотя если открыть базу и сделать такой запрос:
```sql
SELECT tTransaction.*
FROM tTransaction
WHERE (((tTransaction.iConstituentID)=339257) AND ((tTransaction.iResponseID) Is Not Null))
ORDER BY tTransaction.dDate DESC;
```
будет видно, что у человека 3-го апреля была отмена (транзакция с `iResponseID == 64`)

**Comment by shishkovIS** [comment]
Как мы понимаем, что отмена регулярных пожертвований относится к какой-то определенной родительской транзакции. Или же отмена относится ко всем регулярным пожертвованиям данного человека?

**Comment by andrey-makhnutin** [comment]
в `tTransaction.sComment` транзакции отмены записывается id родительской транзакции (`tTransactionProviderData.sProviderData1`)
